version: '3'

services:
  myapp:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: "5050"
    ports:
      - "5050:5050"

  db:
    restart: always
    image: postgres:15.4-alpine3.18
    env_file:
      - .env
    ports:
      - "5432:5432"
